research_task:
  description: >
    Conduct a thorough research about {topic} in home security systems.
    Explore current technologies, innovative solutions, and practical insights 
    for homeowners looking to enhance their residential security.
  expected_output: >
    A list of 10 key research points covering the chosen {topic}, 
    including latest equipment innovations, installation tips, 
    effectiveness statistics, and homeowner recommendations.
  agent: researcher

reporting_task:
  description: >
    Review the context about {topic} in home security systems and 
    develop a comprehensive blog post for homeowners.
    Provide actionable advice, expert insights, and detailed information 
    about residential security solutions.
  expected_output: >
    A fully fledged blog post about {topic} with comprehensive sections 
    focused on home security system technologies and strategies.
    Formatted as markdown without '```'
  agent: blog_writer